apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gqef
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-gqef@sha256:9e3860038a32051fd4dd0922139fa07262c235d8e8c05108c47491ad94ac9b45
        name: my-nodejs
        resources: {}
status: {}
